services:
  - type: web
    name: twilio-relay-ai
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: ELEVEN_API_KEY
        sync: false
      - key: PORT
        sync: false
